# License: MIT
# Copyright © 2023 Frequenz Energy-as-a-Service GmbH

[build-system]
requires = [
  "setuptools == 68.1.0",
  "setuptools_scm[toml] == 7.1.0",
  "frequenz-repo-config[lib] == 0.9.1",
]
build-backend = "setuptools.build_meta"

[project]
name = "pymdownx-superfence-filter-lines"
description = "A custom superfence for pymdown-extensions that can filters lines and plays nice with MkDocs"
readme = "README.md"
license = { text = "MIT" }
keywords = [
  "frequenz",
  "python",
  "lib",
  "library",
  "pymdownx-superfence-filter-lines",
  "markdown",
  "filter",
  "mkdocs",
  "python3",
  "mkdocs-material",
  "pymdownx",
  "pymdown-extensions",
  "superfence",
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Topic :: Software Development :: Libraries",
  "Typing :: Typed",
]
requires-python = ">= 3.11, < 4"
dependencies = ["Markdown >= 3.5, < 4", "pymdown-extensions >= 10, < 11"]
dynamic = ["version"]

[[project.authors]]
name = "Frequenz Energy-as-a-Service GmbH"
email = "floss@frequenz.com"

[project.optional-dependencies]
dev-flake8 = [
  "flake8 == 7.0.0",
  "flake8-docstrings == 1.7.0",
  "flake8-pyproject == 1.2.3",  # For reading the flake8 config from pyproject.toml
  "pydoclint == 0.4.1",
  "pydocstyle == 6.3.0",
]
dev-formatting = ["black == 24.3.0", "isort == 5.13.2"]
dev-mkdocs = [
  "black == 24.3.0",
  "Markdown==3.6",
  "mike == 2.0.0",
  "mkdocs-gen-files == 0.5.0",
  "mkdocs-literate-nav == 0.6.1",
  "mkdocs-macros-plugin == 1.0.5",
  "mkdocs-material == 9.5.16",
  "mkdocstrings[python] == 0.24.1",
  "frequenz-repo-config[lib] == 0.9.1",
]
dev-mypy = [
  "mypy == 1.9.0",
  "types-Markdown == 3.6.0.20240316",
  # For checking the noxfile, docs/ script, and tests
  "pymdownx-superfence-filter-lines[dev-mkdocs,dev-noxfile,dev-pytest]",
]
dev-noxfile = ["nox == 2024.3.2", "frequenz-repo-config[lib] == 0.9.1"]
dev-pylint = [
  "pylint == 3.1.0",
  # For checking the noxfile, docs/ script, and tests
  "pymdownx-superfence-filter-lines[dev-mkdocs,dev-noxfile,dev-pytest]",
]
dev-pytest = [
  "pytest == 8.1.1",
  "frequenz-repo-config[extra-lint-examples] == 0.9.1",
  "pytest-mock == 3.14.0",
  "pytest-asyncio == 0.23.6",
  "async-solipsism == 0.6",
]
dev = [
  "pymdownx-superfence-filter-lines[dev-mkdocs,dev-flake8,dev-formatting,dev-mkdocs,dev-mypy,dev-noxfile,dev-pylint,dev-pytest]",
]

[project.urls]
Documentation = "https://frequenz-floss.github.io/pymdownx-superfence-filter-lines-python/"
Changelog = "https://github.com/frequenz-floss/pymdownx-superfence-filter-lines-python/releases"
Issues = "https://github.com/frequenz-floss/pymdownx-superfence-filter-lines-python/issues"
Repository = "https://github.com/frequenz-floss/pymdownx-superfence-filter-lines-python"
Support = "https://github.com/frequenz-floss/pymdownx-superfence-filter-lines-python/discussions/categories/support"

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 88
src_paths = ["benchmarks", "examples", "src", "tests"]

[tool.flake8]
# We give some flexibility to go over 88, there are cases like long URLs or
# code in documenation that have extra indentation. Black will still take care
# of making everything that can be 88 wide, 88 wide.
max-line-length = 100
extend-ignore = [
  "E203", # Whitespace before ':' (conflicts with black)
  "W503", # Line break before binary operator (conflicts with black)
]
# pydoclint options
style = "google"
check-return-types = false
check-yield-types = false
arg-type-hints-in-docstring = false
arg-type-hints-in-signature = true
allow-init-docstring = true

[tool.pylint.similarities]
ignore-comments = ['yes']
ignore-docstrings = ['yes']
ignore-imports = ['no']
min-similarity-lines = 40

[tool.pylint.messages_control]
disable = [
  "too-few-public-methods",
  # disabled because it conflicts with isort
  "wrong-import-order",
  "ungrouped-imports",
  # pylint's unsubscriptable check is buggy and is not needed because
  # it is a type-check, for which we already have mypy.
  "unsubscriptable-object",
  # Checked by flake8
  "redefined-outer-name",
  "unused-import",
  "line-too-long",
  "unused-variable",
  "unnecessary-lambda-assignment",
]

[tool.pytest.ini_options]
testpaths = ["tests", "src"]
asyncio_mode = "auto"
required_plugins = ["pytest-asyncio", "pytest-mock"]

[tool.mypy]
explicit_package_bases = true
namespace_packages = true
# This option disables mypy cache, and it is sometimes useful to enable it if
# you are getting weird intermittent error, or error in the CI but not locally
# (or vice versa). In particular errors saying that type: ignore is not
# used but getting the original ignored error when removing the type: ignore.
# See for example: https://github.com/python/mypy/issues/2960
#no_incremental = true
modules = ["pymdownx_superfence_filter_lines"]
strict = true

[[tool.mypy.overrides]]
module = ["mkdocs_macros.*", "pymdownx.*", "sybil", "sybil.*"]
ignore_missing_imports = true

[tool.setuptools_scm]
version_scheme = "post-release"
